-- EMPLOYEE TABLES
CREATE TABLE EMPLOYEE (
    EMP_ID VARCHAR(20) PRIMARY KEY,
    EMP_FNAME VARCHAR(50),
    EMP_LNAME VARCHAR(50),
    EMP_DOH DATE,
    EMP_JOBTITLE VARCHAR(50),
    EMP_UNIT VARCHAR(50),
    EMP_CONTACT INT CHECK (EMP_CONTACT > 0),
    EMP_EMAIL VARCHAR(100),
    EMP_STATUS VARCHAR(10)
);
--
SELECT * FROM EMPLOYEE

-- DEPENDENTS TABLES

CREATE TABLE DEPENDENTS (
    DEP_ID VARCHAR(20) PRIMARY KEY,
    EMP_ID VARCHAR(20),
    DEP_LNAME VARCHAR(50),
    DEP_FNAME VARCHAR(50),
    DEP_RELATIONSHIP VARCHAR(50),
    DEP_DOB DATE,
    DEP_CONTACT INT CHECK (DEP_CONTACT > 0),
    DEP_EMAIL VARCHAR(100),
    DEP_STATUS VARCHAR(10),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

--
SELECT * FROM DEPENDENTS

-- PAYMENTS TABLE

CREATE TABLE PAYMENTS ( 
    Payment_ID INT PRIMARY KEY,  
    CUSTOMER_ID INT,  
    Payment_Status VARCHAR2(50), 
    Payment_Amount VARCHAR2(50), 
    Payment_Channel VARCHAR2(50), 
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) 
);

SELECT * FROM PAYMENTS

--

--BILLING TABLE

CREATE TABLE BILLING ( 
    EMP_ID INT PRIMARY KEY, 
    Billing_Status VARCHAR2(50) CHECK (Billing_Status IN ('Active', 'Inactive')), 
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID) 
);

SELECT * FROM BILLING


--

-- COLLECTIONS TABLE

CREATE TABLE COLLECTIONS ( 
    EMP_ID INT PRIMARY KEY, 
    Collection_Status VARCHAR2(50), 
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) 
);

SELECT * FROM COLLECTIONS



 --

 -- CUSTOMER TABLE

CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_STATUS VARCHAR(10),
    CUSTOMER_CONTACT INT CHECK (CUSTOMER_CONTACT > 0),
    CUSTOMER_EMAIL VARCHAR(100),
    CUSTOMER_ADDRESS VARCHAR(200)
);

--
SELECT * FROM CUSTOMER

 -- STATEMENT OF ACCOUNT TABLE
 
 
 CREATE TABLE STATEMENT_OF_ACCOUNT (
    SOA_ID VARCHAR(20) PRIMARY KEY,
    EMP_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    SOA_PERIOD VARCHAR(20),
    SOA_DATE DATE,
    SOA_BALANCE DECIMAL(10, 2),
    SOA_DETAILS VARCHAR(255),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
 
--
SELECT * FROM STATEMENT_OF_ACCOUNT

 -- SUBSCRIPTION TABLE 
 
CREATE TABLE SUBSCRIPTION (
    SUBSCRIPTION_ID VARCHAR(20) PRIMARY KEY,
    SERVICE_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    SUBSCRIPTION_STATUS VARCHAR(10),
    SUBSCRIPTION_START_DATE DATE, 
    SUBSCRIPTION_END_DATE DATE,
    FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE (SERVICE_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

--
SELECT * FROM SUBSCRIPTION

 -- SERVICE TABLE 
 
CREATE TABLE SERVICE (
    SERVICE_ID VARCHAR(20) PRIMARY KEY,
    SERVICE_NAME VARCHAR(100),
    SERVICE_TYPE VARCHAR(50),
    SERVICE_DETAILS VARCHAR(255),
    SERVICE_PRICE DECIMAL(10, 2),
    SERVICE_EQUIPMENT VARCHAR(100)
);
 
 --
SELECT * FROM SERVICE
 
 
 
 
 
 
 
 
 
 
 
 
 
 
  



