-- EMPLOYEE TABLE
CREATE TABLE EMPLOYEE (
    EMP_ID VARCHAR2(20) PRIMARY KEY,
    EMP_FNAME VARCHAR2(50),
    EMP_LNAME VARCHAR2(50),
    EMP_DOH DATE,
    EMP_JOBTITLE VARCHAR2(50),
    EMP_UNIT VARCHAR2(50),
    EMP_CONTACT NUMBER(10) CHECK (EMP_CONTACT > 0),
    EMP_EMAIL VARCHAR2(100),
    EMP_STATUS VARCHAR2(10)
);

-- DEPENDENTS TABLE
CREATE TABLE DEPENDENTS (
    DEP_ID VARCHAR2(20) PRIMARY KEY,
    EMP_ID VARCHAR2(20),
    DEP_LNAME VARCHAR2(50),
    DEP_FNAME VARCHAR2(50),
    DEP_RELATIONSHIP VARCHAR2(50),
    DEP_DOB DATE,
    DEP_CONTACT NUMBER(10) CHECK (DEP_CONTACT > 0),
    DEP_EMAIL VARCHAR2(100),
    DEP_STATUS VARCHAR2(10),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID)
);

-- CUSTOMER TABLE
CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR2(20) PRIMARY KEY,
    CUSTOMER_STATUS VARCHAR2(10),
    CUSTOMER_CONTACT NUMBER(10) CHECK (CUSTOMER_CONTACT > 0),
    CUSTOMER_EMAIL VARCHAR2(100),
    CUSTOMER_ADDRESS VARCHAR2(200)

);

-- SERVICE TABLE
CREATE TABLE SERVICE (
    SERVICE_ID VARCHAR2(20) PRIMARY KEY,
    SERVICE_NAME VARCHAR2(100),
    SERVICE_TYPE VARCHAR2(50),
    SERVICE_DETAILS VARCHAR2(255),
    SERVICE_PRICE NUMBER(10,2),
    SERVICE_EQUIPMENT VARCHAR2(100)
);

-- SUBSCRIPTION TABLE
CREATE TABLE SUBSCRIPTION (
    SUBSCRIPTION_ID VARCHAR2(20) PRIMARY KEY,
    SERVICE_ID VARCHAR2(20),
    CUSTOMER_ID VARCHAR2(20),
    SUBSCRIPTION_STATUS VARCHAR2(10),
    SUBSCRIPTION_START_DATE DATE, 
    SUBSCRIPTION_END_DATE DATE,
    FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE (SERVICE_ID), 
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

-- PAYMENTS TABLE
CREATE TABLE PAYMENTS (
    EMP_ID VARCHAR2(20),
    CUSTOMER_ID VARCHAR2(20),
    PAYMENT_DATE DATE,
    PAYMENT_TYPE VARCHAR2(50),
    PAYMENT_STATUS VARCHAR2(50),
    PAYMENT_AMOUNT NUMBER(10,2),
    PRIMARY KEY (EMP_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

-- BILLING TABLE
CREATE TABLE BILLING (
    EMP_ID VARCHAR2(20),
    CUSTOMER_ID VARCHAR2(20),
    BILLING_STATUS VARCHAR2(50),
    PRIMARY KEY (EMP_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

-- COLLECTION TABLE
CREATE TABLE COLLECTION (
    EMP_ID VARCHAR2(20),
    CUSTOMER_ID VARCHAR2(20),
    COLLECTION_STATUS VARCHAR2(50),
    PRIMARY KEY (EMP_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);

-- STATEMENT OF ACCOUNT TABLE
CREATE TABLE STATEMENT_OF_ACCOUNT (
    SOA_ID VARCHAR2(20) PRIMARY KEY,
    EMP_ID VARCHAR2(20),
    CUSTOMER_ID VARCHAR2(20),
    SOA_PERIOD VARCHAR2(20),
    SOA_DATE DATE,
    SOA_BALANCE NUMBER(10,2),
    SOA_DETAILS VARCHAR2(255),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);