CREATE VIEW customer_statement_of_account AS
SELECT 
    CUSTOMER.CUSTOMER_ID,
    CUSTOMER.CUSTOMER_EMAIL,
    CUSTOMER.CUSTOMER_ADDRESS,
    STATEMENT_OF_ACCOUNT.SOA_ID,
    STATEMENT_OF_ACCOUNT.SOA_PERIOD,
    STATEMENT_OF_ACCOUNT.SOA_DATE,
    STATEMENT_OF_ACCOUNT.SOA_BALANCE,
    STATEMENT_OF_ACCOUNT.SOA_DETAILS
FROM 
    CUSTOMER
JOIN 
    STATEMENT_OF_ACCOUNT ON CUSTOMER.CUSTOMER_ID = STATEMENT_OF_ACCOUNT.CUSTOMER_ID;
