CREATE VIEW customer_subscription_service AS
SELECT 
    CUSTOMER.CUSTOMER_ID,
    CUSTOMER.CUSTOMER_EMAIL,
    CUSTOMER.CUSTOMER_ADDRESS,
    SUBSCRIPTION.SUBSCRIPTION_ID,
    SUBSCRIPTION.SUBSCRIPTION_STATUS,
    SUBSCRIPTION.SUBSCRIPTION_START_DATE,
    SUBSCRIPTION.SUBSCRIPTION_END_DATE,
    SERVICE.SERVICE_ID,
    SERVICE.SERVICE_NAME,
    SERVICE.SERVICE_TYPE,
    SERVICE.SERVICE_DETAILS,
    SERVICE.SERVICE_PRICE
FROM 
    CUSTOMER
JOIN 
    SUBSCRIPTION ON CUSTOMER.CUSTOMER_ID = SUBSCRIPTION.CUSTOMER_ID
JOIN 
    SERVICE ON SUBSCRIPTION.PRODUCT_ID = SERVICE.SERVICE_ID;
