
CREATE VIEW view_customer_status AS  
SELECT   
    CUSTOMER.CUSTOMER_ID,  
    SUBSCRIPTION.Subs_Status AS SUBSCRIPTION_STATUS,  
    SERVICE.SERVICE_TYPE AS SERVICE_TYPE,  
    SERVICE.SERVICE_DETAILS AS SERVICE_DETAILS  
FROM   
    CUSTOMER 
JOIN   
    SUBSCRIPTION ON CUSTOMER.CUSTOMER_ID = SUBSCRIPTION.CUSTOMER_ID  
JOIN   
    SERVICE ON SUBSCRIPTION.SERVICE_ID = SERVICE.SERVICE_ID 
 
;

